name: Deploy on minikube

on:
  push:
    branches:
      - main

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image
#         run: |
#           cd web-app
#           docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up kubectl
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
      - name: Set up kubectl context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: kubeconfig.yaml
          method: kubeconfig
          
      - name: Get pods
        run: kubectl get pods

          
      # - name: Deploy app
      #   run: |
      #     # Replace Minikube IP address in Ingress manifest
      #     kubectl apply -f kubernetes/deployment.yaml
      #     kubectl apply -f kubernetes/service.yaml
      #     # sed "s/minikube-ip-address/${{ secrets.MINIKUBE_IP}}/g" kubernetes/ingress.yaml | kubectl apply -f -
      #     kubectl get pods -A

     
