name: Deploy on minikube

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        run: |
          cd web-app
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
          cd ..
      
      - name: Set up Minikube
        uses: kube-setup-action@v1
        with:
          kubernetes-version: 'latest'
          minikube-version: 'latest'

      - name: Configure kubectl
        run: |
          minikube kubectl -- get pods
          kubectl config use-context minikube
  
      - name: Deploy application
        run: |
          kubectl apply -f deployment.yaml --set=spec.template.spec.containers[0].image=${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml
        
