name: Deploy on minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        run: |
          cd web-app
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
          cd ..
      
      - name: Set up minikube
        uses: kube-setup-action@v1
        with:
          kubernetes-version: 'latest'
          minikube-version: 'latest'

    
