name: Deploy on minikube

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker image
  #       run: |
  #         cd web-app
  #         docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    # needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure kubectl
      run: |
        kubectl config set-cluster minikube --server=https://$MINIKUBE_IP:8443 --certificate-authority=$HOME/.minikube/ca.crt
        kubectl config set-context minikube --cluster=minikube
        kubectl config use-context minikube

    - name: Deploy application
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl apply -f kubernetes/ingress.yaml


          
