name: Deploy on minikube

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker image
  #       run: |
  #         cd web-app
  #         docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up k3s
      uses: steebchen/k3s-action@v0.0.4
      with:
        k3s_version: latest
        kubectl_version: latest
    
    - name: Load Docker image into k3s
      run: |
        docker save ${{ secrets.DOCKERHUB_USERNAME }}/webapp | gzip | k3s ctr images import -
    
    - name: Deploy application
      run: kubectl apply -f deployment.yaml
    
    - name: Expose service
      run: kubectl expose deployment webapp --type=LoadBalancer --port=80 --target-port=5000
    
    - name: Sleep for 5 minutes
      run: sleep 300

          
