name: Deploy on minikube

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker image
  #       run: |
  #         cd web-app
  #         docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml

      - name: Set up GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          mv build/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
          sleep 120


          
