name: Deploy on minikube

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker image
  #       run: |
  #         cd web-app
  #         docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    # needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Minikube directory
      run: mkdir -p /home/runner/.minikube/

    - name: check cert
      run: |
        echo "${{ secrets.CLIENT_CERT }}" 
        echo "${{ secrets.CLIENT_CERT }}" | base64 --decode > /home/runner/.minikube/client_certificate.crt
        cat /home/runner/.minikube/client_certificate.crt

    # - name: Configure kubectl
    #   run: |
    #     echo "$CLIENT_CERTIFICATE" | base64 --decode > /home/runner/.minikube/client_certificate.crt
    #     echo "$CLIENT_KEY" | base64 --decode > /home/runner/.minikube/client_key.key
    #     kubectl config set-cluster minikube --server=https://$MINIKUBE_IP:8443 --certificate-authority=/home/runner/.minikube/client_certificate.crt
    #     kubectl config set-credentials minikube --client-certificate=/home/runner/.minikube/client_certificate.crt --client-key=/home/runner/.minikube/client_key.key
    #     kubectl config set-context minikube --cluster=minikube --user=minikube
    #     kubectl config use-context minikube
    #     kubectl get pods

    # - name: Deploy application
    #   run: |
    #     kubectl apply -f kubernetes/deployment.yaml
    #     kubectl apply -f kubernetes/service.yaml
    #     kubectl apply -f kubernetes/ingress.yaml


          
