name: Deploy on minikube

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd web-app
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: Azure/min-kube@v1

      - name: Deploy to Minikube
        run: |
          # Replace Minikube IP address in Ingress manifest
          export MINIKUBE_IP=$(minikube ip)
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          sed "s/minikube-ip-address/$MINIKUBE_IP/g" kubernetes/ingress.yaml | kubectl apply -f -

      - name: Wait for Ingress Controller
        run: kubectl wait --for=condition=available deployment/nginx-ingress-controller --timeout=300s -n kube-system

      - name: check webapp
        run: curl $MINIKUBE_IP.nip.io

      - name: Wait for deployment to finish
        run: sleep 180 # Wait for 3 minutes

      - name: Display Ingress Rules
        run: kubectl get ingress

          
